name = "ttsg"
pages_build_output_dir = "dist"
compatibility_date = "2025-07-30"
compatibility_flags = ["nodejs_compat"]

[env]
production = { }

# R2 버킷 바인딩 설정
[[r2_buckets]]
bucket_name = "ttsg"
binding = "BUCKET"  # env.BUCKET으로 접근 가능
experimental_remote = true
