name = "ttsg"
pages_build_output_dir = "dist"
compatibility_date = "2025-07-30"
compatibility_flags = ["nodejs_compat"]

# 로컬 개발 환경에서 사용할 R2 버킷 바인딩 설정
[[r2_buckets]]
bucket_name = "ttsg"      # 개발 환경 R2 버킷 이름
binding = "BUCKET"        # env.BUCKET으로 접근 가능

# 개발 환경에서 사용할 R2 버킷 바인딩 설정
[[env.preview.r2_buckets]]
bucket_name = "ttsg"      # 개발 환경 R2 버킷 이름
binding = "BUCKET"        # env.BUCKET으로 접근 가능

# 프로덕션 환경에서 사용할 R2 버킷 바인딩 설정
[[env.production.r2_buckets]]
bucket_name = "ttsg"      # 프로덕션 환경 R2 버킷 이름
binding = "BUCKET"        # env.BUCKET으로 접근 가능
