app = "tt-wiki"
primary_region = "nrt"  # 도쿄 리전 (아시아에서 가장 가까운 리전)

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false  # 항상 실행 상태 유지
  auto_start_machines = true
  min_machines_running = 1

[[mounts]]
  source = "outline_data"
  destination = "/var/lib/outline"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  
  [services.concurrency]
    type = "requests"
    hard_limit = 500
    soft_limit = 400

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "30s"
    restart_limit = 0
    method = "get"
    path = "/healthz"
    protocol = "http"
