# fly.toml app configuration file generated for tt-wiki on 2025-08-13T14:06:51+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tt-wiki'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[[mounts]]
  source = 'outline_data'
  destination = '/var/lib/outline'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'requests'
    hard_limit = 500
    soft_limit = 400

  [[services.http_checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '30s'
    method = 'get'
    path = '/healthz'
    protocol = 'http'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
